---
title: "Compare results"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(here)
```

```{r}
plot_ex <- T # plot an example risk comparisons
cbbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                "#0072B2", "#D55E00", "#CC79A7", "#c5679b", "#be548f")
```


```{r}
filenames <- list.files(
  here('mb-mdr', 'reformatted-data', 'test'), 
  pattern = '*.txt', full.names = F)

sub_name <- function(filetype, my_file){
  gsub('.txt', glue::glue('_{filetype}.txt'), my_file)
}

read_risks <- function(filetype, my_file){
  fread(here('mb-mdr', 'risks', sub_name(filetype, filename)))
}

my_t_test <- function(var){
   t.test(x = cases[, var], y = ctrls[, var], 'greater') %>%
    broom::tidy() %>%
    select(statistic, p.value)
}
```


```{r}
# filename = filenames[3]
i <- 0
t_ori <- tibble()
t_2d <- tibble()
t_1d <- tibble()
# t_ori <- matrix(NA, ncol = 2, nrow = length(filenames))
# t_2d <- vector(mode = 'numeric', length = length(filenames))
# t_1d <- vector(mode = 'numeric', length = length(filenames))
# filename <- filenames[103]
for (filename in filenames){
  i <- i + 1
  # risk_1d <- read_risks('risk_1D', filename)
  risk_2d <- read_risks('risk_2D', filename)
  risk_1d <- risk_2d %>% rename(risk_1d = 'risk_2d') # to be commented out
  risk_ori <- read_risks('risk_ori', filename)
  all_risks <- list(risk_1d, risk_2d, risk_ori) %>%
    reduce(left_join, by = c('Subj', 'Class'))


  
  ctrls <- filter(all_risks, Class == 0)
  cases <- filter(all_risks, Class == 1)
  
  t_ori <- bind_rows(t_ori, my_t_test('risk_ori'))
  t_2d <- bind_rows(t_2d, my_t_test('risk_2d'))
  t_1d <- bind_rows(t_1d, my_t_test('risk_1d'))
  # t_2d[i] <- t.test(x = cases$risk_2d, y = ctrls$risk_2d, 'greater')$statistic
  # t_1d[i] <- t.test(x = -cases$risk_1d, y = -ctrls$risk_1d, 'greater')$statistic
  

}

data.frame(t_ori, t_2d, t_1d) %>%
  gather('RiskType', 'Risk') %>%
  ggplot(aes(x = RiskType, y = Risk)) +
  geom_boxplot()


# which.max(t_2d)

```



```{r}
# plot example
if (plot_ex){ # plot the last comparison
  p_text <- data.frame(
    x = rep(1.5, 3),
    y = c(1.2, 27, 115),
    RiskType = as.factor(c('Original', 'MB-MDR 1D', 'MB-MDR 2D')),
    p = list(t_ori, t_1d, t_2d) %>% 
      sapply(function(x) sprintf("P = %.3g", x[i, 'p.value']))
  )
  
  plot_comp <- all_risks %>%
    gather('RiskType', 'Risk', risk_1d, risk_2d, risk_ori) %>%
    mutate(Class = as.factor(Class) %>% fct_recode(Healthy = '0', Case = '1')) %>%
    mutate(RiskType = fct_recode(RiskType, 
                                 `MB-MDR 1D` = 'risk_1d', 
                                 `MB-MDR 2D` = 'risk_2d',
                                 Original = 'risk_ori')) %>%
    ggplot(aes(x = Class, y = Risk)) +
    facet_wrap(~ RiskType, scale = 'free') +
    # geom_violin(aes(fill = Class), scale = 'width', alpha = 0.5) +
    geom_boxplot(aes(color = Class)) +
    geom_jitter(aes(color = Class),
                height = 0, width = 0.1, alpha = 0.1, stroke = 0) +
    scale_color_brewer(palette = 'Dark2') +
    theme_bw() +
    labs(x = NULL) +
    theme(legend.position = 'None') + 
    geom_text(p_text, mapping = aes(x = x, y = y, label = p) , size = 3)
  plot_comp
  plot_comp %>% ggsave(filename = 'plot_comp.pdf', height = 3, width = 5)
}
  
```


TO BE FINISHED
```{r}
library(ROCit)
## Warning: package 'ROCit' was built under R version 3.5.2
ROCit_obj <- rocit(score=all_risks$risk_ori, all_risks$Class)
ROCit_obj$AUC
plot(ROCit_obj)

roc_df <- data.frame(aupr = c(auroc_relief_cc, auroc_npdr_cc , auroc_rf_cc),
                    type = rep(c('RRelief', 'NPDR', 'Random forest'), each = n_sims))
roc_df$type <- factor(roc_df$type, levels = rev(levels(roc_df$type)))

roc_compare_relief <- t.test(auroc_npdr_cc, auroc_relief_cc)
roc_compare_rf <- t.test(auroc_npdr_cc, auroc_rf_cc)
print(roc_compare_relief$p.value)
roc_p <- round(roc_compare_relief$p.value, 3)
print(roc_compare_rf$p.value)


ss_npdr <- pROC::roc(test.df$functional, test.df$beta.Z.att)
ss_relief <- pROC::roc(test.df$functional, test.df$rrelief)
ss_rf <- pROC::roc(rf_imp_cc$functional, rf_imp_cc$MeanDecreaseAccuracy)
  
  
```



```{r}
roc_func <- function(risk_type){
  PRROC::roc.curve(scores.class0 = all_risks[, risk_type],
                   weights.class0 = all_risks$Class,
                   curve = T)
}

pr_func <- function(risk_type){
  PRROC::pr.curve(scores.class0 = all_risks[, risk_type],
                   weights.class0 = all_risks$Class,
                   curve = T)
}
# case_risks <- filter(all_risks, Class == 1)
# ctrl_risks <- filter(all_risks, Class == 0)
pr_ori <- pr_func('risk_ori')
pr_2d <- pr_func('risk_2d')
pr_1d <- pr_func('risk_1d')
  
roc_ori <- roc_func('risk_ori')
roc_2d <- roc_func('risk_2d')
roc_1d <- roc_func('risk_1d')

pr_ori$auc.integral
```

```{r}
pr_text <- data.frame(
  label = c(
    paste0('Original risk \n', c(round(pr_ori$auc.integral, 3))),
    paste0('MB-MDR 1D \n ', round(pr_1d$auc.integral, 3)),
    paste0('MB-MDR 2D \n', round(pr_2d$auc.integral, 3))
    # paste0('NPDR\n', round(auprc_npdr_qtrait, 3)),
    # paste0('NPDR\n   ', round(auprc_npdr_cc, 3))
    ),
  # sim = rep(c('Continuous outcome', 'Dichotomous outcome'), 3),
  x = c(0.3, 0.6, 0.3),
  y = c(0.45, 0.65, 0.78),
  type = c('Original', '1D', '2D')
)

prr_ori <- as.data.frame(pr_ori$curve)
colnames(prr_ori) <- paste0(c('Recall', 'Precision', 'w'))
prr_2d <- as.data.frame(pr_2d$curve)
colnames(prr_2d) <- paste0(c('Recall', 'Precision', 'w'))
prr_1d <- as.data.frame(pr_1d$curve)
colnames(prr_1d) <- paste0(c('Recall', 'Precision', 'w'))

pr <- rbind(prr_ori, prr_2d, prr_1d) %>% 
  mutate(type = c(rep('Original', nrow(prr_ori)), 
                  rep('2D', nrow(prr_2d)),
                  rep('1D', nrow(prr_1d)))) %>%
  ggplot(aes(Recall, Precision, color = type)) +
  geom_path(size = 0.8) + theme_bw() + 
  scale_color_manual(values = cbbPalette[c(8,3,6)]) +
  scale_x_continuous(limits = c(0, 1.05), breaks = seq(0, 1.1, 0.2), labels = scales::percent) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2), labels = scales::percent) +
  geom_text(pr_text, mapping = aes(x = x, y = y, label = label), size = 3) +
  coord_fixed(ratio = 1) +
  guides(color = FALSE)

ggsave(pr, filename = 'figs/test1.pdf', height = 4, width = 4)
```


auROC:

```{r}
roc_text <- data.frame(
  label = c(
    paste0('Original risk \n', c(round(roc_ori$auc, 3))),
    paste0('MB-MDR 1D \n ', round(roc_1d$auc, 3)),
    paste0('MB-MDR 2D \n', round(roc_2d$auc, 3))
    # paste0('NPDR\n', round(aurocc_npdr_qtrait, 3)),
    # paste0('NPDR\n   ', round(aurocc_npdr_cc, 3))
    ),
  # sim = rep(c('Continuous outcome', 'Dichotomous outcome'), 3),
  x = c(0.55, 0.2 , 0.45),
  y = c(0.4, 0.5, 0.75),
  type = c('Original', '1D', '2D')
)

rocr_ori <- as.data.frame(roc_ori$curve)
colnames(rocr_ori) <- paste0(c('Recall', 'Precision', 'w'))
rocr_2d <- as.data.frame(roc_2d$curve)
colnames(rocr_2d) <- paste0(c('Recall', 'Precision', 'w'))
rocr_1d <- as.data.frame(roc_1d$curve)
colnames(rocr_1d) <- paste0(c('Recall', 'Precision', 'w'))

roc <- rbind(rocr_ori, rocr_2d, rocr_1d) %>% 
  mutate(type = c(rep('Original', nrow(rocr_ori)), 
                  rep('2D', nrow(rocr_2d)),
                  rep('1D', nrow(rocr_1d)))) %>%
  # mutate(sim = c(rep('Continuous outcome', nrow(roc_qtrait)), 
  #                rep('Dichotomous outcome', nrow(roc_cc)))) %>%
  ggplot(aes(Recall, Precision, color = type)) +
  geom_path(size = 0.8) + theme_bw() + 
  scale_color_manual(values = cbbPalette[c(8,3,6)]) +
  scale_x_continuous(limits = c(0, 1.05), breaks = seq(0, 1.1, 0.2), labels = scales::percent) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2), labels = scales::percent) +
  geom_text(roc_text, mapping = aes(x = x, y = y, label = label), size = 3) +
  coord_fixed(ratio = 1) +
  guides(color = FALSE)
roc

ggsave(roc, filename = 'figs/test1.pdf', height = 4, width = 4)

```

