---
title: "Read in results"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(here)
# also use: glue
```

## Methods
Each subject risk score = chi_sq * (their value (HLO) at snp1_snp2)

```{r}
rm(list = ls())
row_2d <- 14

filenames <- list.files(here('mb-mdr', 'reformatted-data', 'test'), 
                        pattern = '*.txt', full.names = F)

sub_name <- function(filetype, my_file){
  gsub('.txt', glue::glue('_{filetype}.txt'), my_file)
}

for (filename in filenames){
  # (filename <- filenames[3])
  mod_file <- sub_name('model_2D', filename)
  out_file <- sub_name('output_2D', filename)
  risk_file <- sub_name('risk_2D', filename)
  
  # read in test data
  dat <- here('mb-mdr', 'reformatted-data', 'test', filename) %>% 
    fread() %>% 
    data.frame()
  snp_dat <- select(dat, - Class)
  
  # read in models
  raw_model <- here('mb-mdr', 'results', mod_file) %>%
    fread(fill = T, header = F) %>%
    data.frame()
  chisq_df <- here('mb-mdr', 'results', out_file) %>%
    fread(header = F, skip = 3, 
          col.names = c('ma1', 'ma2', 'chi_sq', 'p_val')) %>%
    mutate(ma_names = paste(ma1, ma2, sep = '_'))
  
  # parse data
  nrow_model <- floor((nrow(raw_model) + 1)/row_2d)
  mdr_model <- list()
  
  for (i in seq(nrow_model)){
    idx <- row_2d * (i-1) + 1
    ma_names <- paste(raw_model[idx, 1:2], collapse = '_')
    mdr_model[[ma_names]] <- list(
      affected = as_tibble(raw_model[idx + (2:4), ]),
      unaffected = as_tibble(raw_model[idx + (6:8), ]),
      HLO = as_tibble(raw_model[idx + (10:12), ]) %>%
        map_df(~ recode(.x, L = -1, H = 1, O = 0)) %>%
        as.matrix()
    )
  }
  
  # calculate risk
  risk_2d <- vector(mode = 'numeric', length = nrow(snp_dat))
  
  for (subj_idx in seq(nrow(snp_dat))){
    sum = 0
    for (i in seq(nrow(chisq_df))){
      ma_pair <- chisq_df$ma_names[i] # e.g. X1_X2
      chi_sq <- chisq_df$chi_sq[i] # chi-squared values of that SNP comb
      mas <- strsplit(ma_pair, '_') %>% unlist # SNPs names, e.g. c('X1', 'X2')
      snp1_val <- snp_dat[subj_idx, mas[1]]
      snp2_val <- snp_dat[subj_idx, mas[2]]
      
      hlo <- mdr_model[[ma_pair]]$HLO
      sum <- sum + hlo[snp1_val + 1, snp2_val + 1]*chi_sq # check order here
    }
    risk_2d[subj_idx] <- sum
  }
  
  result_df <- data.frame(risk_2d, dat) 
  # result_df %>%
  #   mutate(Class = as.factor(Class)) %>%
  #   ggplot(aes(x = Class, y = risk_score, fill = Class)) +
  #   geom_boxplot()
  
  cor.test(result_df$Class, result_df$risk_2d)
  
  result_df %>% 
    rownames_to_column('Subj') %>%
    dplyr::select(Subj, Class, risk_2d) %>%
    fwrite(here('mb-mdr', 'risks', risk_file))
  
}
```


Q: How compatible is this compared to -d 1D? 3D?
TODO: split into training + testing
What about thresholding?
