---
title: "Read in results"
output: html_document
---

```{r}
library(data.table)
# library(tidyverse)
# library(here)
# also use: glue
```

```{r}
sub_name <- function(filetype, my_file){
  gsub('.txt', glue::glue('_{filetype}.txt'), my_file) %>% 
    gsub('test', 'train', .)
}

```


## Methods
Each subject risk score = chi_sq * (their value (HLO) at snp1_snp2)

```{r}
# rm(list = ls())
row_1d <- 7
p_threshold <- 1
filename <- 'reformat_heart_failure_test.txt'

mod_file <- sub_name('model_1D', filename)
out_file <- sub_name('output_1D', filename)
risk_file <- sub_name('risk_1D', filename)

# read in test data
dat <- 
  data.table::fread(paste0('mb-mdr/reformatted-data/heart-failure/', filename)) %>% 
  data.frame()
snp_dat <- select(dat, contains('rs'))

# read in models
raw_model <- here('mb-mdr', 'results', mod_file) %>%
  read.table(stringsAsFactors = F, fill = T)

chisq_df <- here('mb-mdr', 'results', out_file) %>%
  data.table::fread(header = F, skip = 3, 
                    col.names = c('ma1', 'chi_sq', 'p_val'))
nrow_model <- nrow(chisq_df)

# parse data
mdr_model <- list()
for (i in seq(nrow_model)){
  idx <- row_1d * (i-1) + 1
  ma_names <- raw_model[idx, 1]
  mdr_model[[ma_names]] <- list(
    affected = as_tibble(raw_model[idx + 2, ]),
    unaffected = as_tibble(raw_model[idx + 4, ]),
    HLO = as_tibble(raw_model[idx + 6, ]) %>%
      purrr::map_df(~ recode(.x, L = -1, H = 1, O = 0)) %>%
      as.matrix()
  )
}

# calculate risk
risk_1d <- vector(mode = 'numeric', length = nrow(snp_dat))

for (subj_idx in seq(nrow(snp_dat))){
  sum = 0
  for (j in seq(nrow(chisq_df))){
    if (chisq_df$p_val[j] < p_threshold){
      ma <- chisq_df$ma1[j] # e.g. X4
      chi_sq <- chisq_df$chi_sq[j] # chi-squared values of that SNP comb
      
      snp1_val <- snp_dat[subj_idx, ma]
      hlo <- mdr_model[[ma]]$HLO
      sum <- sum + hlo[snp1_val + 1]*chi_sq # check order here
    }
  }
  risk_1d[subj_idx] <- sum
}

result_df <- data.frame(risk_1d, dat) 

result_df %>% 
  tibble::rownames_to_column('Subj') %>%
  dplyr::select(Subj, PHENOTYPE, risk_1d) %>%
  fwrite(here('mb-mdr', 'risks', paste0('p', p_threshold), risk_file))

cor.test(result_df$PHENOTYPE, result_df$risk_1d)


```

2D

```{r}
row_2d <- 13

filename <- 'reformat_heart_failure_test.txt'

mod_file <- sub_name('model_2D', filename)
out_file <- sub_name('output_2D', filename)
risk_file <- sub_name('risk_2D', filename)

# read in test data
dat <- 
  data.table::fread(paste0('mb-mdr/reformatted-data/heart-failure/', filename)) %>% 
  data.frame()
snp_dat <- select(dat, contains('rs'))

# read in models
raw_model <- here('mb-mdr', 'results', mod_file) %>%
  read.table(fill = T, stringsAsFactors = F, header = F)

chisq_df <- here('mb-mdr', 'results', out_file) %>%
  data.table::fread(header = F, skip = 3, 
          col.names = c('ma1', 'ma2', 'chi_sq', 'p_val')) %>%
    mutate(ma_names = paste(ma1, ma2, sep = '_'))
nrow_model <- nrow(chisq_df)

# parse data
mdr_model <- list()

for (i in seq(nrow_model)){
  idx <- row_2d * (i-1) + 1
  ma_names <- paste(raw_model[idx, 1:2], collapse = '_')
  mdr_model[[ma_names]] <- list(
    affected = as_tibble(raw_model[idx + (2:4), ]),
    unaffected = as_tibble(raw_model[idx + (6:8), ]),
    HLO = as_tibble(raw_model[idx + (10:12), ]) %>%
      purrr::map_df(~ recode(.x, L = -1, H = 1, O = 0)) %>%
      as.matrix()
  )
}

# calculate risk
risk_2d <- vector(mode = 'numeric', length = nrow(snp_dat))

for (subj_idx in seq(nrow(snp_dat))){
  sum = 0
  for (j in seq(nrow(chisq_df))){
    if (chisq_df$p_val[j] < p_threshold){
      ma_pair <- chisq_df$ma_names[j] # e.g. X1_X2
      chi_sq <- chisq_df$chi_sq[j] # chi-squared values of that SNP comb
      mas <- strsplit(ma_pair, '_') %>% unlist # SNPs names, e.g. c('X1', 'X2')
      snp1_val <- snp_dat[subj_idx, mas[1]]
      snp2_val <- snp_dat[subj_idx, mas[2]]
      
      hlo <- mdr_model[[ma_pair]]$HLO
      sum <- sum + hlo[snp1_val + 1, snp2_val + 1]*chi_sq # check order here
    }
  }
  risk_2d[subj_idx] <- sum
}

result_df <- data.frame(risk_2d, dat) 
# result_df %>%
#   mutate(Class = as.factor(Class)) %>%
#   ggplot(aes(x = Class, y = risk_score, fill = Class)) +
#   geom_boxplot()

cor.test(result_df$PHENOTYPE, result_df$risk_2d)

result_df %>% 
  tibble::rownames_to_column('Subj') %>%
  dplyr::select(Subj, PHENOTYPE, risk_2d) %>%
  fwrite(here('mb-mdr', 'risks', paste0('p', p_threshold), risk_file))

```

